import type { Message, PersonRecommendation, Song } from "@/lib/product-types";

export const sampleSongs: Song[] = [
  {
    id: "song-archive-1",
    title: "Late Room Demo",
    artist: "Mara Vale",
    caption: "rough mix for the archive #cloudrap",
    duration: "2:48",
    fileType: "mp3",
    source: "archive",
    visibility: "private",
    tags: ["cloudrap", "demo", "night"],
    likes: 18,
    comments: 4,
    reposts: 2,
    color: "#1256ff",
  },
  {
    id: "song-archive-2",
    title: "Basement Static",
    artist: "Northline",
    caption: "guitar take with drums #punkrock",
    duration: "3:12",
    fileType: "wav",
    source: "archive",
    visibility: "private",
    tags: ["punkrock", "garage", "guitar"],
    likes: 9,
    comments: 2,
    reposts: 1,
    color: "#ff6f61",
  },
  {
    id: "song-public-1",
    title: "Signal Bloom",
    artist: "Ari Sol",
    caption: "public upload for synth heads #indiepop",
    duration: "3:35",
    fileType: "flac",
    source: "public",
    visibility: "public",
    tags: ["indiepop", "synth", "new"],
    likes: 247,
    comments: 31,
    reposts: 44,
    color: "#20a67a",
  },
  {
    id: "song-shared-1",
    title: "Noon Loop",
    artist: "J. Harbor",
    caption: "sent in a private DM #housemusic",
    duration: "4:02",
    fileType: "mp4",
    source: "shared",
    visibility: "private",
    tags: ["housemusic", "loop", "dm"],
    likes: 54,
    comments: 8,
    reposts: 5,
    color: "#f2b84b",
  },
];

export const peopleYouShouldFollow: PersonRecommendation[] = [
  {
    id: "person-1",
    name: "Mina Coast",
    handle: "@minacoast",
    reason: "#cloudrap and private demos",
    verified: true,
    color: "#1256ff",
  },
  {
    id: "person-2",
    name: "Rowan Key",
    handle: "@rowankey",
    reason: "mutual archive saves",
    verified: false,
    color: "#ff6f61",
  },
  {
    id: "person-3",
    name: "Sable FM",
    handle: "@sablefm",
    reason: "#punkrock uploads",
    verified: true,
    color: "#20a67a",
  },
];

export const sampleMessages: Message[] = [
  {
    id: "message-1",
    sender: "Mina Coast",
    body: "This is the kind of playable message the app has to support.",
    sentAt: "2:14 PM",
    song: sampleSongs[3],
    reactions: ["🔥", "🎧"],
  },
  {
    id: "message-2",
    sender: "You",
    body: "Saving this to the shared queue.",
    sentAt: "2:16 PM",
    reactions: ["✅"],
  },
];
